spring:
  application:
    name: demo-consumer2

server:
  port: 7002

feign:              #配置Feign Hystrix熔断
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/